/**
 * Декларативные схемы свойств объектов метаданных.
 *
 * Идея: всё, что панель свойств показывает по XML-фрагменту объекта —
 * это упорядоченный список ключей из блока `<Properties>`. Наборы ключей
 * и правила их отображения описываются тут, а не в хэндлерах.
 *
 * При добавлении нового набора свойств нужно:
 *   1) добавить ключ → подпись в `PROPERTY_TITLE_RU` (если отсутствует);
 *   2) при необходимости — расширить множества в `BOOLEAN_PROPERTY_TAGS` /
 *      `LOCALIZED_PROPERTY_TAGS` / enum-опции;
 *   3) зарегистрировать `PropertySchema` в `PROPERTY_SCHEMAS`;
 *   4) привязать схему к типу через поле `propertySchema` в `META_TYPES`.
 */

/** Опция enum-свойства (например, FillChecking, Indexing) */
export interface EnumPropertyOption {
  value: string;
  label: string;
}

/** Набор допустимых enum-значений по ключу */
export type EnumOptionsMap = Readonly<Record<string, readonly EnumPropertyOption[]>>;

/** Описание схемы свойств: упорядоченный список XML-ключей */
export interface PropertySchema {
  /** Технический идентификатор схемы (соответствует META_TYPES.propertySchema) */
  id: string;
  /** Порядок ключей при отрисовке */
  keys: readonly string[];
  /**
   * Источник XML: целый фрагмент элемента (берём `<Properties>` внутри) или
   * уже извлечённая внутренность `<Properties>`. По умолчанию — «фрагмент элемента».
   */
  source?: 'element' | 'propertiesInner';
}

/** Теги со строкой локализации (v8:item/v8:lang/v8:content) */
export const LOCALIZED_PROPERTY_TAGS: ReadonlySet<string> = new Set([
  'Synonym',
  'Comment',
  'Caption',
  'ShortCaption',
  'BriefInformation',
  'DetailedInformation',
  'Copyright',
  'VendorInformationAddress',
  'ConfigurationInformationAddress',
  'ToolTip',
  'ObjectPresentation',
  'ExtendedObjectPresentation',
  'ListPresentation',
  'ExtendedListPresentation',
  'Explanation',
  'ExtendedExplanation',
]);

/** Теги булевых свойств */
export const BOOLEAN_PROPERTY_TAGS: ReadonlySet<string> = new Set([
  'PasswordMode',
  'MarkNegatives',
  'MultiLine',
  'ExtendedEdit',
  'FillFromFillingValue',
  'DenyIncompleteValues',
  'ShowInTotal',
  'UseStandardCommands',
  'IncludeHelpInContents',
  'Modality',
  'ModifiesData',
  'Use',
  'Predefined',
  'Global',
  'ClientManagedApplication',
  'Server',
  'ExternalConnection',
  'ClientOrdinaryApplication',
  'ServerCall',
  'Privileged',
  'SetForNewObjects',
  'SetForAttributesByDefault',
  'IndependentRightsOfChildObjects',
  'CheckUnique',
  'Autonumbering',
  'Hierarchical',
  'LimitLevelCount',
  'FoldersOnTop',
  'IncludeConfigurationExtensions',
  'MainFilterOnPeriod',
  'EnableTotalsSliceFirst',
  'EnableTotalsSliceLast',
  'EnableTotalsSplitting',
  'Correspondence',
  'CreateTaskInPrivilegedMode',
  'Addressing',
  'TaskNumberAutoPrefix',
  'AutoOrderByCode',
  'DistributedInfoBase',
  'ThisNodeBelongsToExchangePlan',
  'SendData',
  'ReceiveData',
  'SequentialDataExchange',
  'PostInPrivilegedMode',
  'UnpostInPrivilegedMode',
  'KeepMappingToExtendedConfigurationObjectsByIDs',
  'UseManagedFormInOrdinaryApplication',
  'UseOrdinaryFormInManagedApplication',
  'UpdateDataHistoryImmediatelyAfterWrite',
  'ExecuteAfterWriteDataHistoryVersionProcessing',
]);

/** Опции команды командного интерфейса (свойство Group) */
const COMMAND_INTERFACE_GROUP_OPTIONS: readonly EnumPropertyOption[] = [
  { value: 'NavigationPanelImportant', label: 'Панель навигации: важное' },
  { value: 'NavigationPanelOrdinary', label: 'Панель навигации: обычное' },
  { value: 'NavigationPanelSeeAlso', label: 'Панель навигации: см. также' },
  { value: 'ActionsPanelCreate', label: 'Панель действий: создать' },
  { value: 'ActionsPanelReports', label: 'Панель действий: отчёты' },
  { value: 'ActionsPanelTools', label: 'Панель действий: сервис' },
  { value: 'FormNavigationPanelImportant', label: 'Панель навигации формы: важное' },
  { value: 'FormNavigationPanelGoTo', label: 'Панель навигации формы: перейти' },
  { value: 'FormNavigationPanelSeeAlso', label: 'Панель навигации формы: см. также' },
  { value: 'FormCommandBarImportant', label: 'Командная панель формы: важное' },
  { value: 'FormCommandBarCreateBasedOn', label: 'Командная панель формы: создать на основании' },
];

/** Режим совместимости платформы (единый набор для нескольких свойств конфигурации) */
const COMPATIBILITY_MODE_OPTIONS: readonly EnumPropertyOption[] = [
  { value: 'DontUse', label: 'Не использовать' },
  { value: 'Version8_1', label: 'Версия 8.1' },
  { value: 'Version8_2_13', label: 'Версия 8.2.13' },
  { value: 'Version8_2_16', label: 'Версия 8.2.16' },
  { value: 'Version8_3_1', label: 'Версия 8.3.1' },
  { value: 'Version8_3_2', label: 'Версия 8.3.2' },
  { value: 'Version8_3_3', label: 'Версия 8.3.3' },
  { value: 'Version8_3_4', label: 'Версия 8.3.4' },
  { value: 'Version8_3_5', label: 'Версия 8.3.5' },
  { value: 'Version8_3_6', label: 'Версия 8.3.6' },
  { value: 'Version8_3_7', label: 'Версия 8.3.7' },
  { value: 'Version8_3_8', label: 'Версия 8.3.8' },
  { value: 'Version8_3_9', label: 'Версия 8.3.9' },
  { value: 'Version8_3_10', label: 'Версия 8.3.10' },
  { value: 'Version8_3_11', label: 'Версия 8.3.11' },
  { value: 'Version8_3_12', label: 'Версия 8.3.12' },
  { value: 'Version8_3_13', label: 'Версия 8.3.13' },
  { value: 'Version8_3_14', label: 'Версия 8.3.14' },
  { value: 'Version8_3_15', label: 'Версия 8.3.15' },
  { value: 'Version8_3_16', label: 'Версия 8.3.16' },
  { value: 'Version8_3_17', label: 'Версия 8.3.17' },
  { value: 'Version8_3_18', label: 'Версия 8.3.18' },
  { value: 'Version8_3_19', label: 'Версия 8.3.19' },
  { value: 'Version8_3_20', label: 'Версия 8.3.20' },
  { value: 'Version8_3_21', label: 'Версия 8.3.21' },
  { value: 'Version8_3_22', label: 'Версия 8.3.22' },
  { value: 'Version8_3_23', label: 'Версия 8.3.23' },
  { value: 'Version8_3_24', label: 'Версия 8.3.24' },
  { value: 'Version8_3_25', label: 'Версия 8.3.25' },
  { value: 'Version8_3_26', label: 'Версия 8.3.26' },
  { value: 'Version8_3_27', label: 'Версия 8.3.27' },
  { value: 'Version8_3_28', label: 'Версия 8.3.28' },
  { value: 'Version8_5_1', label: 'Версия 8.5.1' },
];

/**
 * Допустимые enum-значения по ключу свойства. Единый источник опций для панели
 * свойств и MCP: и UI-рендер, и контракт инструментов читают именно этот реестр.
 */
export const ENUM_OPTIONS: EnumOptionsMap = {
  FillChecking: [
    { value: 'DontCheck', label: 'Не проверять' },
    { value: 'ShowError', label: 'Выдавать ошибку' },
    { value: 'ShowWarning', label: 'Показывать предупреждение' },
  ],
  Indexing: [
    { value: 'DontIndex', label: 'Не индексировать' },
    { value: 'Index', label: 'Индексировать' },
    { value: 'IndexWithAdditionalOrder', label: 'Индексировать с дополнительным упорядочиванием' },
  ],
  CodeAllowedLength: [
    { value: 'Variable', label: 'Переменная' },
    { value: 'Fixed', label: 'Фиксированная' },
  ],
  NumberAllowedLength: [
    { value: 'Variable', label: 'Переменная' },
    { value: 'Fixed', label: 'Фиксированная' },
  ],
  CodeType: [
    { value: 'String', label: 'Строка' },
    { value: 'Number', label: 'Число' },
  ],
  NumberType: [
    { value: 'String', label: 'Строка' },
    { value: 'Number', label: 'Число' },
  ],
  CodeSeries: [
    { value: 'WholeCatalog', label: 'Во всём справочнике' },
    { value: 'WithinSubordination', label: 'В пределах подчинения' },
    { value: 'WithinOwnerSubordination', label: 'В пределах подчинения владельцу' },
    { value: 'WholeCharacteristicKind', label: 'Во всём виде характеристик' },
    { value: 'WholeChartOfAccounts', label: 'Во всём плане счетов' },
  ],
  NumberPeriodicity: [
    { value: 'Nonperiodical', label: 'Непериодический' },
    { value: 'Year', label: 'Год' },
    { value: 'Quarter', label: 'Квартал' },
    { value: 'Month', label: 'Месяц' },
    { value: 'Day', label: 'День' },
  ],
  ChoiceFoldersAndItems: [
    { value: 'Items', label: 'Элементы' },
    { value: 'Folders', label: 'Группы' },
    { value: 'FoldersAndItems', label: 'Группы и элементы' },
  ],
  ChoiceHistoryOnInput: [
    { value: 'Auto', label: 'Автоматически' },
    { value: 'DontUse', label: 'Не использовать' },
  ],
  QuickChoice: [
    { value: 'Auto', label: 'Автоматически' },
    { value: 'DontUse', label: 'Не использовать' },
    { value: 'Use', label: 'Использовать' },
  ],
  CreateOnInput: [
    { value: 'Auto', label: 'Автоматически' },
    { value: 'DontUse', label: 'Не использовать' },
    { value: 'Use', label: 'Использовать' },
  ],
  FullTextSearch: [
    { value: 'DontUse', label: 'Не использовать' },
    { value: 'Use', label: 'Использовать' },
  ],
  FullTextSearchOnInputByString: [
    { value: 'DontUse', label: 'Не использовать' },
    { value: 'Use', label: 'Использовать' },
  ],
  DataHistory: [
    { value: 'DontUse', label: 'Не использовать' },
    { value: 'Use', label: 'Использовать' },
  ],
  SearchStringModeOnInputByString: [
    { value: 'Begin', label: 'С начала строки' },
    { value: 'AnyPart', label: 'Любая часть строки' },
  ],
  ChoiceDataGetModeOnInputByString: [
    { value: 'Directly', label: 'Непосредственно' },
  ],
  DefaultPresentation: [
    { value: 'AsCode', label: 'В виде кода' },
    { value: 'AsDescription', label: 'В виде наименования' },
  ],
  EditType: [
    { value: 'InList', label: 'В списке' },
    { value: 'InDialog', label: 'В диалоге' },
    { value: 'BothWays', label: 'Обоими способами' },
  ],
  Posting: [
    { value: 'Allow', label: 'Разрешить' },
    { value: 'Deny', label: 'Запретить' },
  ],
  RealTimePosting: [
    { value: 'Allow', label: 'Разрешить' },
    { value: 'Deny', label: 'Запретить' },
  ],
  RegisterRecordsDeletion: [
    { value: 'AutoDelete', label: 'Удалять автоматически' },
    { value: 'AutoDeleteOnUnpost', label: 'Удалять автоматически при отмене проведения' },
    { value: 'AutoDeleteOff', label: 'Не удалять автоматически' },
  ],
  RegisterRecordsWritingOnPost: [
    { value: 'WriteSelected', label: 'Записывать выбранные' },
    { value: 'WriteModified', label: 'Записывать изменённые' },
  ],
  SequenceFilling: [
    { value: 'AutoFill', label: 'Заполнять автоматически' },
    { value: 'AutoFillOff', label: 'Не заполнять автоматически' },
  ],
  ChoiceMode: [
    { value: 'FromForm', label: 'Из формы' },
    { value: 'QuickChoice', label: 'Быстрый выбор' },
    { value: 'BothWays', label: 'Обоими способами' },
  ],
  FormType: [
    { value: 'Managed', label: 'Управляемая' },
  ],
  Representation: [
    { value: 'Auto', label: 'Автоматически' },
    { value: 'Text', label: 'Текст' },
    { value: 'Picture', label: 'Картинка' },
    { value: 'PictureAndText', label: 'Картинка и текст' },
  ],
  Group: COMMAND_INTERFACE_GROUP_OPTIONS,
  TemplateType: [
    { value: 'SpreadsheetDocument', label: 'Табличный документ' },
    { value: 'TextDocument', label: 'Текстовый документ' },
    { value: 'HTMLDocument', label: 'HTML-документ' },
    { value: 'BinaryData', label: 'Двоичные данные' },
    { value: 'DataCompositionSchema', label: 'Схема компоновки данных' },
    { value: 'DataCompositionAppearanceTemplate', label: 'Шаблон оформления компоновки данных' },
    { value: 'GraphicalSchema', label: 'Графическая схема' },
    { value: 'AddIn', label: 'Внешняя компонента' },
  ],
  UseInInterfaceCompatibilityMode: [
    { value: 'Any', label: 'Любой' },
    { value: 'Version85', label: 'Версия 8.5' },
  ],
  RegisterType: [
    { value: 'Balance', label: 'Остатки' },
    { value: 'Turnovers', label: 'Обороты' },
  ],
  InformationRegisterPeriodicity: [
    { value: 'Nonperiodical', label: 'Непериодический' },
    { value: 'Second', label: 'Секунда' },
    { value: 'Day', label: 'День' },
    { value: 'Month', label: 'Месяц' },
    { value: 'Quarter', label: 'Квартал' },
    { value: 'Year', label: 'Год' },
    { value: 'RecorderPosition', label: 'Позиция регистратора' },
  ],
  WriteMode: [
    { value: 'Independent', label: 'Независимый' },
    { value: 'RecorderSubordinate', label: 'Подчинение регистратору' },
  ],
  ReturnValuesReuse: [
    { value: 'DontUse', label: 'Не использовать' },
    { value: 'DuringRequest', label: 'На время вызова' },
    { value: 'DuringSession', label: 'На время сеанса' },
  ],
  ReuseSessions: [
    { value: 'AutoUse', label: 'Использовать автоматически' },
    { value: 'DontUse', label: 'Не использовать' },
    { value: 'Use', label: 'Использовать' },
  ],
  ParameterUseMode: [
    { value: 'Single', label: 'Одиночный' },
    { value: 'Multiple', label: 'Множественный' },
  ],
  OnMainServerUnavalableBehavior: [
    { value: 'Auto', label: 'Авто' },
    { value: 'DontChangeBehavior', label: 'Не изменять поведение' },
  ],
  HierarchyType: [
    { value: 'HierarchyFoldersAndItems', label: 'Иерархия групп и элементов' },
    { value: 'HierarchyOfItems', label: 'Иерархия элементов' },
  ],
  SubordinationUse: [
    { value: 'ToItems', label: 'Элементам' },
    { value: 'ToFolders', label: 'Группам' },
    { value: 'ToFoldersAndItems', label: 'Группам и элементам' },
  ],
  AutoUse: [
    { value: 'DontUse', label: 'Не использовать' },
    { value: 'Use', label: 'Использовать' },
  ],
  PredefinedDataUpdate: [
    { value: 'Auto', label: 'Автоматически' },
    { value: 'AutoUpdate', label: 'Автообновление' },
    { value: 'DontAutoUpdate', label: 'Не обновлять автоматически' },
  ],
  HTTPMethod: [
    { value: 'GET', label: 'GET' },
    { value: 'HEAD', label: 'HEAD' },
    { value: 'PUT', label: 'PUT' },
    { value: 'POST', label: 'POST' },
    { value: 'DELETE', label: 'DELETE' },
    { value: 'PATCH', label: 'PATCH' },
    { value: 'MERGE', label: 'MERGE' },
    { value: 'OPTIONS', label: 'OPTIONS' },
    { value: 'TRACE', label: 'TRACE' },
    { value: 'CONNECT', label: 'CONNECT' },
    { value: 'PROPFIND', label: 'PROPFIND' },
    { value: 'PROPPATCH', label: 'PROPPATCH' },
    { value: 'MOVE', label: 'MOVE' },
    { value: 'COPY', label: 'COPY' },
    { value: 'LOCK', label: 'LOCK' },
    { value: 'UNLOCK', label: 'UNLOCK' },
    { value: 'MKCOL', label: 'MKCOL' },
    { value: 'Any', label: 'Любой' },
  ],
  CompatibilityMode: COMPATIBILITY_MODE_OPTIONS,
  ConfigurationExtensionCompatibilityMode: COMPATIBILITY_MODE_OPTIONS,
  ConfigurationExtensionPurpose: [
    { value: 'Patch', label: 'Исправление' },
    { value: 'Customization', label: 'Адаптация' },
    { value: 'AddOn', label: 'Дополнение' },
  ],
  DefaultRunMode: [
    { value: 'ManagedApplication', label: 'Управляемое приложение' },
    { value: 'OrdinaryApplication', label: 'Обычное приложение' },
    { value: 'Auto', label: 'Автоматически' },
  ],
  ScriptVariant: [
    { value: 'Russian', label: 'Русский' },
    { value: 'English', label: 'Английский' },
  ],
  DataLockControlMode: [
    { value: 'Automatic', label: 'Автоматический' },
    { value: 'Managed', label: 'Управляемый' },
    { value: 'AutomaticAndManaged', label: 'Автоматический и управляемый' },
  ],
  ObjectAutonumerationMode: [
    { value: 'NotAutoFree', label: 'Не освобождать автоматически' },
    { value: 'AutoFree', label: 'Освобождать автоматически' },
  ],
  ModalityUseMode: [
    { value: 'DontUse', label: 'Не использовать' },
    { value: 'Use', label: 'Использовать' },
    { value: 'UseWithWarnings', label: 'Использовать с предупреждениями' },
  ],
  SynchronousPlatformExtensionAndAddInCallUseMode: [
    { value: 'DontUse', label: 'Не использовать' },
    { value: 'Use', label: 'Использовать' },
    { value: 'UseWithWarnings', label: 'Использовать с предупреждениями' },
  ],
  InterfaceCompatibilityMode: [
    { value: 'Version8_2', label: 'Версия 8.2' },
    { value: 'Version8_2EnableTaxi', label: 'Версия 8.2 с возможностью Такси' },
    { value: 'Taxi', label: 'Такси' },
    { value: 'TaxiEnableVersion8_2', label: 'Такси с возможностью версии 8.2' },
    { value: 'TaxiEnableVersion8_5', label: 'Такси с возможностью версии 8.5' },
    { value: 'Version8_5EnableTaxi', label: 'Версия 8.5 с возможностью Такси' },
    { value: 'Version8_5', label: 'Версия 8.5' },
  ],
  Version85InterfaceMigrationMode: [
    { value: 'DontUse', label: 'Не использовать' },
    { value: 'Use', label: 'Использовать' },
  ],
  DatabaseTablespacesUseMode: [
    { value: 'DontUse', label: 'Не использовать' },
    { value: 'Use', label: 'Использовать' },
  ],
  MainClientApplicationWindowMode: [
    { value: 'Normal', label: 'Обычный' },
    { value: 'Fullscreen', label: 'Полноэкранный' },
    { value: 'Kiosk', label: 'Киоск' },
  ],
  MainClientApplicationWindowInterfaceVariant: [
    { value: 'NavigationLeft', label: 'Панель разделов слева' },
    { value: 'NavigationTop', label: 'Панель разделов сверху' },
  ],
  ClientApplicationTheme: [
    { value: 'Auto', label: 'Автоматически' },
    { value: 'Light', label: 'Светлая' },
    { value: 'Dark', label: 'Тёмная' },
  ],
  ClientApplicationWindowsOpenVariant: [
    { value: 'OpenDataInTabs', label: 'Открывать в закладках' },
    { value: 'OpenDataInSeparateWindows', label: 'Открывать в отдельных окнах' },
  ],
};

/** Опции назначения использования (свойство UsePurposes, множественный выбор) */
export const USE_PURPOSE_OPTIONS: readonly EnumPropertyOption[] = [
  { value: 'PlatformApplication', label: 'Приложение платформы' },
  { value: 'MobilePlatformApplication', label: 'Мобильное приложение' },
];

/** Значения enum-свойств по умолчанию, когда тег отсутствует, но ключ пришёл в схеме */
export const ENUM_DEFAULTS: Readonly<Record<string, string>> = {
  FillChecking: 'DontCheck',
  Indexing: 'DontIndex',
  CodeAllowedLength: 'Variable',
  NumberAllowedLength: 'Variable',
  CodeType: 'String',
  NumberType: 'String',
  CodeSeries: 'WholeCatalog',
  NumberPeriodicity: 'Nonperiodical',
  DefaultPresentation: 'AsDescription',
  EditType: 'InDialog',
  Posting: 'Allow',
  RealTimePosting: 'Deny',
  RegisterRecordsDeletion: 'AutoDelete',
  RegisterRecordsWritingOnPost: 'WriteSelected',
  SequenceFilling: 'AutoFill',
  ChoiceMode: 'FromForm',
  FormType: 'Managed',
  Representation: 'Auto',
  TemplateType: 'SpreadsheetDocument',
  RegisterType: 'Balance',
  InformationRegisterPeriodicity: 'Nonperiodical',
  WriteMode: 'Independent',
  ReturnValuesReuse: 'DontUse',
  ReuseSessions: 'DontUse',
  ParameterUseMode: 'Single',
  OnMainServerUnavalableBehavior: 'Auto',
  HierarchyType: 'HierarchyFoldersAndItems',
  SubordinationUse: 'ToItems',
  AutoUse: 'DontUse',
  PredefinedDataUpdate: 'Auto',
};

/** Русские подписи известных тегов свойств */
export const PROPERTY_TITLE_RU: Readonly<Record<string, string>> = {
  Name: 'Имя',
  Synonym: 'Синоним',
  Comment: 'Комментарий',
  Caption: 'Заголовок приложения',
  ShortCaption: 'Краткий заголовок приложения',
  BriefInformation: 'Краткая информация',
  DetailedInformation: 'Подробная информация',
  Copyright: 'Авторские права',
  VendorInformationAddress: 'Адрес информации о поставщике',
  ConfigurationInformationAddress: 'Адрес информации о конфигурации',
  Type: 'Тип',
  Source: 'Источник',
  PasswordMode: 'Режим пароля',
  Format: 'Формат',
  EditFormat: 'Формат редактирования',
  ToolTip: 'Подсказка',
  Picture: 'Картинка',
  MarkNegatives: 'Отметка отрицательных',
  Mask: 'Маска',
  MultiLine: 'Многострочный режим',
  ExtendedEdit: 'Расширенное редактирование',
  MinValue: 'Минимальное значение',
  MaxValue: 'Максимальное значение',
  FillFromFillingValue: 'Заполнять из данных заполнения',
  FillValue: 'Значение заполнения',
  FillChecking: 'Проверка заполнения',
  ChoiceFoldersAndItems: 'Выбор групп и элементов',
  ChoiceParameterLinks: 'Связи параметров выбора',
  ChoiceParameters: 'Параметры выбора',
  ChoiceForm: 'Форма выбора',
  QuickChoice: 'Быстрый выбор',
  CreateOnInput: 'Создание при вводе',
  ChoiceHistoryOnInput: 'История выбора при вводе',
  Indexing: 'Индексирование',
  FullTextSearch: 'Полнотекстовый поиск',
  DataHistory: 'История данных',
  LinkByType: 'Связь по типу',
  DenyIncompleteValues: 'Запрет неполного ввода',
  RoundingMode: 'Режим округления',
  ShowInTotal: 'Показывать итог',
  LineNumberLength: 'Длина номера строки',
  StandardAttributes: 'Стандартные реквизиты',
  ObjectBelonging: 'Владение объектом',
  ExtendedConfigurationObject: 'Расширенный объект конфигурации',
  ConfigurationExtensionPurpose: 'Назначение расширения',
  KeepMappingToExtendedConfigurationObjectsByIDs: 'Сохранять соответствие объектам по идентификаторам',
  NamePrefix: 'Префикс имён',
  ConfigurationExtensionCompatibilityMode: 'Режим совместимости расширений конфигурации',
  CompatibilityMode: 'Режим совместимости',
  DefaultRunMode: 'Основной режим запуска',
  UsePurposes: 'Назначение использования',
  ScriptVariant: 'Вариант встроенного языка',
  DefaultRoles: 'Основные роли',
  Vendor: 'Поставщик',
  Version: 'Версия',
  UpdateCatalogAddress: 'Адрес каталога обновлений',
  UseManagedFormInOrdinaryApplication: 'Использовать управляемые формы в обычном приложении',
  UseOrdinaryFormInManagedApplication: 'Использовать обычные формы в управляемом приложении',
  AdditionalFullTextSearchDictionaries: 'Дополнительные словари полнотекстового поиска',
  CommonSettingsStorage: 'Общее хранилище настроек',
  ReportsUserSettingsStorage: 'Хранилище пользовательских настроек отчётов',
  ReportsVariantsStorage: 'Хранилище вариантов отчётов',
  FormDataSettingsStorage: 'Хранилище настроек данных форм',
  DynamicListsUserSettingsStorage: 'Хранилище пользовательских настроек динамических списков',
  URLExternalDataStorage: 'Адрес внешнего хранилища данных',
  Content: 'Содержимое',
  DefaultReportForm: 'Основная форма отчёта',
  DefaultReportVariantForm: 'Основная форма варианта отчёта',
  DefaultReportSettingsForm: 'Основная форма настроек отчёта',
  DefaultReportAppearanceTemplate: 'Основной шаблон оформления отчёта',
  DefaultDynamicListSettingsForm: 'Основная форма настроек динамического списка',
  DefaultSearchForm: 'Основная форма поиска',
  DefaultDataHistoryChangeHistoryForm: 'Основная форма истории изменений',
  DefaultDataHistoryVersionDataForm: 'Основная форма данных версии',
  DefaultDataHistoryVersionDifferencesForm: 'Основная форма различий версий',
  DefaultCollaborationSystemUsersChoiceForm: 'Основная форма выбора пользователей системы взаимодействия',
  AuxiliaryReportForm: 'Дополнительная форма отчёта',
  AuxiliaryReportVariantForm: 'Дополнительная форма варианта отчёта',
  AuxiliaryReportSettingsForm: 'Дополнительная форма настроек отчёта',
  AuxiliaryDynamicListSettingsForm: 'Дополнительная форма настроек динамического списка',
  AuxiliaryDataHistoryChangeHistoryForm: 'Дополнительная форма истории изменений',
  AuxiliaryDataHistoryVersionDataForm: 'Дополнительная форма данных версии',
  AuxiliaryDataHistoryVersionDifferencesForm: 'Дополнительная форма различий версий',
  AuxiliaryCollaborationSystemUsersChoiceForm: 'Дополнительная форма выбора пользователей системы взаимодействия',
  RequiredMobileApplicationPermissions: 'Требуемые разрешения мобильного приложения',
  UsedMobileApplicationFunctionalities: 'Используемые возможности мобильного приложения',
  StandaloneConfigurationRestrictionRoles: 'Роли ограничения автономной конфигурации',
  MobileApplicationURLs: 'URL мобильного приложения',
  AllowedIncomingShareRequestTypes: 'Разрешённые типы входящих запросов обмена',
  MainClientApplicationWindowInterfaceVariant: 'Вариант интерфейса основного окна клиентского приложения',
  ClientApplicationTheme: 'Тема клиентского приложения',
  MainClientApplicationWindowMode: 'Режим основного окна клиентского приложения',
  ClientApplicationWindowsOpenVariant: 'Вариант открытия окон клиентского приложения',
  DefaultInterface: 'Основной интерфейс',
  DefaultStyle: 'Основной стиль',
  DefaultLanguage: 'Основной язык',
  ObjectAutonumerationMode: 'Режим автоосвобождения номеров',
  ModalityUseMode: 'Режим использования модальности',
  SynchronousPlatformExtensionAndAddInCallUseMode: 'Режим синхронных вызовов расширений платформы и внешних компонент',
  InterfaceCompatibilityMode: 'Режим совместимости интерфейса',
  Version85InterfaceMigrationMode: 'Режим перехода интерфейса версии 8.5',
  DatabaseTablespacesUseMode: 'Режим использования табличных пространств базы данных',
  DefaultConstantsForm: 'Основная форма констант',
  CodeLength: 'Длина кода',
  CodeAllowedLength: 'Допустимая длина кода',
  CodeSeries: 'Серия кодов',
  CheckUnique: 'Контроль уникальности',
  Autonumbering: 'Автонумерация',
  DefaultPresentation: 'Основное представление',
  EditType: 'Способ редактирования',
  CodeType: 'Тип кода',
  DefaultObjectForm: 'Основная форма объекта',
  DefaultRecordForm: 'Основная форма записи',
  DefaultListForm: 'Основная форма списка',
  DefaultChoiceForm: 'Основная форма выбора',
  AuxiliaryObjectForm: 'Дополнительная форма объекта',
  AuxiliaryRecordForm: 'Дополнительная форма записи',
  AuxiliaryListForm: 'Дополнительная форма списка',
  AuxiliaryChoiceForm: 'Дополнительная форма выбора',
  InputByString: 'Ввод по строке',
  SearchStringModeOnInputByString: 'Режим строки поиска при вводе по строке',
  FullTextSearchOnInputByString: 'Полнотекстовый поиск при вводе по строке',
  ChoiceDataGetModeOnInputByString: 'Режим получения данных при вводе по строке',
  Characteristics: 'Характеристики',
  BasedOn: 'Вводится на основании',
  BasedFor: 'Является основанием для',
  StandardTabularSections: 'Стандартные табличные части',
  DistributedInfoBase: 'Распределённая информационная база',
  ThisNodeBelongsToExchangePlan: 'Узел принадлежит плану обмена',
  SendData: 'Отправка данных',
  ReceiveData: 'Получение данных',
  SequentialDataExchange: 'Последовательный обмен данными',
  Numerator: 'Нумератор',
  NumberType: 'Тип номера',
  NumberLength: 'Длина номера',
  NumberAllowedLength: 'Допустимая длина номера',
  NumberPeriodicity: 'Периодичность номера',
  Posting: 'Проведение',
  RealTimePosting: 'Оперативное проведение',
  RegisterRecordsDeletion: 'Удаление движений',
  RegisterRecordsWritingOnPost: 'Запись движений при проведении',
  SequenceFilling: 'Заполнение последовательностей',
  RegisterRecords: 'Движения',
  PostInPrivilegedMode: 'Проведение в привилегированном режиме',
  UnpostInPrivilegedMode: 'Отмена проведения в привилегированном режиме',
  Group: 'Группа командного интерфейса',
  CommandParameterType: 'Тип параметра команды',
  Representation: 'Представление',
  Modality: 'Модальность',
  IncludeHelpInContents: 'Включать справку в содержимое',
  FormType: 'Тип формы',
  UseStandardCommands: 'Использовать стандартные команды',
  DefaultForm: 'Основная форма',
  ExtendedPresentation: 'Расширенное представление',
  ChoiceMode: 'Режим выбора',
  Color: 'Цвет',
  ObjectPresentation: 'Представление объекта',
  ExtendedObjectPresentation: 'Расширенное представление объекта',
  ListPresentation: 'Представление списка',
  ExtendedListPresentation: 'Расширенное представление списка',
  Explanation: 'Пояснение',
  ExtendedExplanation: 'Расширенное пояснение',
  DataLockControlMode: 'Режим управления блокировкой данных',
  TemplateType: 'Тип макета',
  UseInInterfaceCompatibilityMode: 'Использовать в режиме совместимости интерфейса',
  RegisterType: 'Вид регистра',
  InformationRegisterPeriodicity: 'Периодичность регистра сведений',
  WriteMode: 'Режим записи',
  UseInTotals: 'Использовать в итогах',
  EnableTotalsSplitting: 'Разрешить разделение итогов',
  EnableTotalsSliceFirst: 'Разрешить итоги среза первых',
  EnableTotalsSliceLast: 'Разрешить итоги среза последних',
  ReturnValuesReuse: 'Повторное использование возвращаемых значений',
  ReuseSessions: 'Повторное использование сеансов',
  Server: 'Сервер',
  ExternalConnection: 'Внешнее соединение',
  ClientManagedApplication: 'Клиент управляемого приложения',
  ClientOrdinaryApplication: 'Клиент обычного приложения',
  Privileged: 'Привилегированный',
  Global: 'Глобальный',
  FunctionalOption: 'Функциональная опция',
  ParameterUseMode: 'Режим использования параметра',
  Hierarchical: 'Иерархический',
  HierarchyType: 'Вид иерархии',
  LimitLevelCount: 'Ограничение количества уровней иерархии',
  LevelCount: 'Количество уровней иерархии',
  FoldersOnTop: 'Группы сверху',
  SubordinationUse: 'Использование подчинения',
  Owners: 'Владельцы',
  DescriptionLength: 'Длина наименования',
  DefaultFolderForm: 'Основная форма группы',
  DefaultFolderChoiceForm: 'Основная форма выбора группы',
  AuxiliaryFolderForm: 'Дополнительная форма группы',
  AuxiliaryFolderChoiceForm: 'Дополнительная форма выбора группы',
  DataLockFields: 'Поля блокировки данных',
  ExtDimensionAccountingFlag: 'Признак учёта субконто',
  Balance: 'Баланс',
  AccountingFlag: 'Признак учёта',
  AutoUse: 'Автоиспользование',
  DataSeparation: 'Разделение данных',
  DataSeparationValue: 'Значение разделения данных',
  DataSeparationUse: 'Использование разделения данных',
  UsersSeparation: 'Разделение пользователей',
  AuthenticationSeparation: 'Разделение аутентификации',
  ConfigurationExtensionsSeparation: 'Разделение расширений конфигурации',
  SeparatedDataUse: 'Использование разделённых данных',
  IncludeConfigurationExtensions: 'Включать расширения конфигурации',
  PredefinedDataUpdate: 'Обновление предопределённых данных',
  Predefined: 'Предопределённый',
  Use: 'Использовать',
  MethodName: 'Имя метода',
  ModifiesData: 'Изменяет данные',
  OnMainServerUnavalableBehavior: 'Поведение при недоступности основного сервера',
  Shortcut: 'Сочетание клавиш',
  Transactioned: 'Транзакционный',
  UpdateDataHistoryImmediatelyAfterWrite: 'Обновлять историю данных сразу после записи',
  ExecuteAfterWriteDataHistoryVersionProcessing: 'Выполнять обработку версии истории данных после записи',
  HTTPMethod: 'HTTP-метод',
  RootURL: 'Корневой URL',
  SessionMaxAge: 'Время жизни сеанса',
  Template: 'Шаблон',
  Handler: 'Обработчик',
  Event: 'Событие',
  ProcedureName: 'Имя процедуры',
};

// ── Наборы ключей по типам ─────────────────────────────────────────────

const COMMON_ROOT_KEYS = [
  'Name',
  'Synonym',
  'Comment',
  'ObjectBelonging',
  'ExtendedConfigurationObject',
  'DefaultObjectForm',
  'DefaultRecordForm',
  'DefaultListForm',
  'DefaultChoiceForm',
  'AuxiliaryObjectForm',
  'AuxiliaryRecordForm',
  'AuxiliaryListForm',
  'AuxiliaryChoiceForm',
  'InputByString',
  'SearchStringModeOnInputByString',
  'FullTextSearchOnInputByString',
  'ChoiceDataGetModeOnInputByString',
  'CreateOnInput',
  'ChoiceHistoryOnInput',
  'DataLockControlMode',
  'FullTextSearch',
  'ObjectPresentation',
  'ExtendedObjectPresentation',
  'ListPresentation',
  'ExtendedListPresentation',
  'Explanation',
  'BasedOn',
] as const;

const ENUM_ROOT_KEYS = [
  'Name',
  'Synonym',
  'Comment',
  'ObjectBelonging',
  'ExtendedConfigurationObject',
  'UseStandardCommands',
  'QuickChoice',
  'ChoiceMode',
  'DefaultListForm',
  'DefaultChoiceForm',
  'AuxiliaryListForm',
  'AuxiliaryChoiceForm',
  'ListPresentation',
  'ExtendedListPresentation',
  'Explanation',
  'ChoiceHistoryOnInput',
] as const;

const EXCHANGE_PLAN_ROOT_EXTRA = [
  'CodeLength',
  'CodeAllowedLength',
  'CodeSeries',
  'CheckUnique',
  'Autonumbering',
  'DefaultPresentation',
  'EditType',
  'Characteristics',
  'StandardAttributes',
  'StandardTabularSections',
  'DistributedInfoBase',
  'ThisNodeBelongsToExchangePlan',
  'SendData',
  'ReceiveData',
  'SequentialDataExchange',
] as const;

const TYPED_FIELD_KEYS = [
  'Name',
  'Synonym',
  'Comment',
  'Type',
  'PasswordMode',
  'Format',
  'EditFormat',
  'ToolTip',
  'MarkNegatives',
  'Mask',
  'MultiLine',
  'ExtendedEdit',
  'MinValue',
  'MaxValue',
  'FillFromFillingValue',
  'FillValue',
  'FillChecking',
  'ChoiceFoldersAndItems',
  'ChoiceParameterLinks',
  'ChoiceForm',
  'QuickChoice',
  'CreateOnInput',
  'ChoiceHistoryOnInput',
  'Indexing',
  'FullTextSearch',
  'DataHistory',
  'LinkByType',
  'DenyIncompleteValues',
  'RoundingMode',
  'ShowInTotal',
] as const;

const STANDARD_ATTRIBUTE_KEYS = TYPED_FIELD_KEYS.filter((key) => key !== 'Type');

const TABULAR_SECTION_KEYS = [
  'Name',
  'Synonym',
  'Comment',
  'ToolTip',
  'FillChecking',
  'StandardAttributes',
  'LineNumberLength',
] as const;

const FORM_KEYS = ['Name', 'Synonym', 'Comment', 'FormType', 'IncludeHelpInContents', 'UseStandardCommands'] as const;
const COMMAND_KEYS = [
  'Name',
  'Synonym',
  'Comment',
  'Group',
  'CommandParameterType',
  'ParameterUseMode',
  'ModifiesData',
  'OnMainServerUnavalableBehavior',
  'Representation',
  'ToolTip',
  'Shortcut',
  'Picture',
  'IncludeHelpInContents',
] as const;
const ENUM_VALUE_KEYS = ['Name', 'Synonym', 'Comment', 'Color'] as const;
const TEMPLATE_KEYS = ['Name', 'Synonym', 'Comment', 'TemplateType'] as const;
const SCHEDULED_JOB_KEYS = ['Name', 'Synonym', 'Comment', 'MethodName', 'Use', 'Predefined'] as const;

/** Реестр схем по ключу `META_TYPES.propertySchema` */
export const PROPERTY_SCHEMAS: Readonly<Record<string, PropertySchema>> = {
  catalog: { id: 'catalog', keys: COMMON_ROOT_KEYS, source: 'propertiesInner' },
  document: { id: 'document', keys: COMMON_ROOT_KEYS, source: 'propertiesInner' },
  exchangePlan: {
    id: 'exchangePlan',
    keys: [...COMMON_ROOT_KEYS, ...EXCHANGE_PLAN_ROOT_EXTRA],
    source: 'propertiesInner',
  },
  enumRoot: { id: 'enumRoot', keys: ENUM_ROOT_KEYS, source: 'propertiesInner' },

  typedField: { id: 'typedField', keys: TYPED_FIELD_KEYS, source: 'element' },
  standardAttribute: { id: 'standardAttribute', keys: STANDARD_ATTRIBUTE_KEYS, source: 'element' },
  tabularSection: { id: 'tabularSection', keys: TABULAR_SECTION_KEYS, source: 'element' },
  form: { id: 'form', keys: FORM_KEYS, source: 'element' },
  command: { id: 'command', keys: COMMAND_KEYS, source: 'element' },
  enumValue: { id: 'enumValue', keys: ENUM_VALUE_KEYS, source: 'element' },
  template: { id: 'template', keys: TEMPLATE_KEYS, source: 'element' },
  urlTemplate: { id: 'urlTemplate', keys: ['Name', 'Synonym', 'Comment', 'Template'], source: 'element' },
  httpMethod: { id: 'httpMethod', keys: ['Name', 'Synonym', 'Comment', 'HTTPMethod', 'Handler'], source: 'element' },
  scheduledJob: { id: 'scheduledJob', keys: SCHEDULED_JOB_KEYS, source: 'propertiesInner' },

  // схемы для корневых «общих» объектов — включают сравнительно небольшой набор полей
  constant: {
    id: 'constant',
    keys: [
      'Name',
      'Synonym',
      'Comment',
      'Type',
      'Format',
      'EditFormat',
      'ToolTip',
      'FillChecking',
      'ChoiceFoldersAndItems',
      'ChoiceParameterLinks',
      'ChoiceForm',
    ],
    source: 'propertiesInner',
  },
  sessionParameter: {
    id: 'sessionParameter',
    keys: ['Name', 'Synonym', 'Comment', 'Type'],
    source: 'propertiesInner',
  },
  commonAttribute: {
    id: 'commonAttribute',
    keys: ['Name', 'Synonym', 'Comment', 'Type', 'Format', 'EditFormat', 'ToolTip', 'FillValue', 'FillChecking'],
    source: 'propertiesInner',
  },
};
